theme: jekyll-theme-minimal
title: Open Broadway Data â€“ Archive Site
description: "The project is currently archived, with limited ongoing development."
google_analytics: UA-177940998-1
logo: images/open-broadway-data-logo.png
logo_alt: Open Broadway Data logo
plugins:
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme

### Build settings ###
github: [metadata]
repository: Open-Broadway-Data/static-website
baseurl: ""
url: https://openbroadwaydata.com
